# Generated by Django 5.0.1 on 2024-02-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=50)),
                ('type', models.CharField(choices=[('t', 'Tenis'), ('p', 'Pádel')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('category', models.CharField(choices=[('Infant', 'Infant'), ('Junior', 'Junior'), ('Adult', 'Adult'), ('Senior', 'Senior')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.court')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.member')),
            ],
        ),
    ]
