# Generated by Django 5.0.1 on 2024-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
